repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        language_version: python3

  - repo: local
    hooks:
      - id: forbid-legacy-slugs
        name: forbid legacy slugs
        # exit non-zero if any match is found
        entry: bash -lc "rg -n '(vaultmesh-mesh|infra-servers|infra-dns|(^|/)forge(/|$)|(^|/)ops(/|$)|(^|/)cmd(/|$))' \
                         --glob '!**/logs/**' --glob '!**/.git/**' --glob '!**/node_modules/**' \
                         --glob '!**/vendor/**' --glob '!**/target/**' && exit 1 || exit 0"
        language: system
        pass_filenames: false
