name: shared-lint

on:
  workflow_call: {}
  workflow_dispatch: {}
  push:
    branches: [ main ]

jobs:
  lint:
    name: Lint (ruff + eslint + pre-commit)
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      # ---------- Python (ruff / pre-commit Python hooks) ----------
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
        continue-on-error: true

      - name: Install ruff & pre-commit (Python)
        run: |
          python -m pip install --upgrade pip
          pip install ruff pre-commit
        continue-on-error: true

      - name: Run ruff (if python files present)
        run: |
          if git ls-files '*.py' | grep -q .; then
            ruff --version
            ruff check .
          else
            echo "No Python files; skipping ruff."
          fi
        continue-on-error: false

      # ---------- Node (eslint / Prettier via pre-commit, if present) ----------
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
        continue-on-error: true

      - name: Enable pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate
        continue-on-error: true

      - name: Install JS deps (if package.json exists)
        run: |
          if [ -f package.json ]; then
            pnpm install --frozen-lockfile || pnpm install
          else
            echo "No package.json; skipping pnpm install."
          fi
        continue-on-error: true

      - name: Run eslint (if configured)
        run: |
          if [ -f package.json ] && npx --yes eslint --version >/dev/null 2>&1; then
            npx --yes eslint . || (echo "eslint found issues" && exit 1)
          else
            echo "eslint not configured; skipping."
          fi

      # ---------- pre-commit (repo-wide hygiene) ----------
      - name: Run pre-commit (if config present)
        run: |
          if [ -f .pre-commit-config.yaml ]; then
            pre-commit run --all-files
          else
            echo "No .pre-commit-config.yaml; skipping."
          fi
