name: shared-security

on:
  workflow_call: {}
  workflow_dispatch: {}
  schedule:
    - cron: '0 2 * * 1'

jobs:
  security-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Node Audit (npm / pnpm)
        shell: bash
        run: |
          if [ -f package.json ]; then
            corepack enable || true
            corepack prepare pnpm@latest --activate || true
            pnpm -v || npm i -g pnpm || true
            pnpm audit --prod || echo "audit found issues – review output"
          else
            echo "no package.json – skip npm audit"
          fi

      - name: Python Audit (pip-audit)
        shell: bash
        run: |
          python3 -m pip install --upgrade pip || true
          pip3 install pip-audit || true
          (pip-audit || true)

      - name: Rust Audit (cargo-audit)
        shell: bash
        run: |
          if [ -f Cargo.toml ]; then
            rustup toolchain install stable -y || true
            cargo install cargo-audit || true
            (cargo audit || true)
          else
            echo "no Cargo.toml – skip cargo audit"
          fi

      - name: Dependency Review (GitHub)
        uses: actions/dependency-review-action@v4
